-- MySQL Script generated by MySQL Workbench
-- 08/05/16 13:11:32
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema attendance_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema attendance_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `attendance_db` DEFAULT CHARACTER SET utf8 ;
USE `attendance_db` ;

-- -----------------------------------------------------
-- Table `attendance_db`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `attendance_db`.`admin` (
  `admin_id` INT NOT NULL,
  `admin_class` VARCHAR(14) NOT NULL,
  `card_id` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`admin_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `attendance_db`.`instructor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `attendance_db`.`instructor` (
  `instructor_id` INT NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `card_id` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`instructor_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `attendance_db`.`course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `attendance_db`.`course` (
  `course_id` INT NOT NULL,
  `course_title` VARCHAR(45) NOT NULL,
  `course_code` VARCHAR(45) NOT NULL,
  `instructor_id` INT NOT NULL,
  PRIMARY KEY (`course_id`),
  CONSTRAINT `instructor_id`
    FOREIGN KEY (`instructor_id`)
    REFERENCES `attendance_db`.`instructor` (`instructor_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `instructor_id_idx` ON `attendance_db`.`course` (`instructor_id` ASC);


-- -----------------------------------------------------
-- Table `attendance_db`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `attendance_db`.`student` (
  `student_id` INT NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `matric_no` VARCHAR(14) NOT NULL,
  `card_id` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`student_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `attendance_db`.`attend_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `attendance_db`.`attend_log` (
  `course_id` INT NOT NULL,
  `student_id` INT NOT NULL,
  `date` DATE NOT NULL,
  `time_in` DATE NOT NULL,
  PRIMARY KEY (`course_id`, `student_id`),
  CONSTRAINT `course_id`
    FOREIGN KEY (`course_id`)
    REFERENCES `attendance_db`.`course` (`course_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `student_id`
    FOREIGN KEY (`student_id`)
    REFERENCES `attendance_db`.`student` (`student_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `student_id_idx` ON `attendance_db`.`attend_log` (`student_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
